name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Install dependencies
      run: dotnet restore src/DenonControl.Web/DenonControl.Web.csproj
    - name: Build
      run: dotnet build src/DenonControl.Web/DenonControl.Web.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test src/DenonControl.Web/DenonControl.Web.csproj --no-restore --verbosity normal
